---
- name: Deploy example app to my-server.com
  hosts: all
  become: yes

  vars:
#    ansistrano_deploy_from: "{{ playbook_dir }}/../my-app"
#    ansistrano_deploy_to: "/tmp/my-app.com"
    ansistrano_keep_releases: 3
    # There seems to be an issue with rsync in vagrant
    ansistrano_deploy_via: copy
  roles:
    - role: carlosbuenosvinos.ansistrano-deploy
      vars:
        ansistrano_deploy_from: "{{project_dir}}/frontend"
        ansistrano_deploy_to: "{{ deploy_base_path }}"

    - role: carlosbuenosvinos.ansistrano-deploy
      vars:
        ansistrano_deploy_from: "{{project_dir}}/backend"
        ansistrano_deploy_to: "{{ deploy_base_path }}"