---
#machines
machines: []

#ansible
ansible_python_interpreter: "/usr/bin/python3"

#vagrant
vagrant_version_min: '2.1.1'
vagrant_provider: virtualbox
vagrant_box: ubuntu/xenial64
vagrant_private_ip: "192.168.10.10"
vagrant_memory: 1024
vagrant_cpus: 1
vagrant_vm_user: vagrant

vagrant_folder_default_type: nfs

vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostmanager
  - name: digitalocean


#drupalvm_ansible_version_min: '2.4'


# MySQL databases and users.
mysql_databases:
  - name: "{{ db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
#    priv: "*.*:USAGE"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ db_name }}"

postgresql_users:
  - name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    priv: "ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras: []

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

firewall_enabled: true
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "2200"
  - "80"
  - "443"


firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true


#git
git_version: "2.17.1"

#pip
# For Python 3, use python3-pip.
pip_package: python3-pip

pip_install_packages: []


# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.2"
php_install_recommends: no
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

php_enable_webserver: true
php_enable_php_fpm: true
php_date_timezone: "Europe/Madrid"
php_webserver_daemon: openresty

php_fpm_listen: "127.0.0.1:9000"

php_packages_extra:
  - "php{{ php_version }}-zip"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ vagrant_vm_user }}/.composer"
composer_home_owner: "{{ vagrant_vm_user }}"
composer_home_group: "{{ vagrant_vm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }


# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x", "6.x".
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: npm
nodejs_install_npm_user: "{{ vagrant_vm_user }}"
npm_config_prefix: "/home/{{ vagrant_vm_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ vagrant_vm_user }}"
ruby_install_gems: []


# Varnish Configuration (if enabled above).
varnish_listen_port: "6081"
varnish_default_vcl_template_path: "{{origami_dir}}/templates/varnish/default.vlc.j2"
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "8080"

# Pimp my Log settings.
pimpmylog_install_dir: "{{ nginx_root_base_path }}/{{ hostname }}/pimpmylog"
pimpmylog_grant_all_privs: no

# PhpRedmi
phpredmin_install_dir: "{{ nginx_root_base_path }}/{{ hostname }}/phpredmin"

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"

# Solr Configuration (if enabled above).
solr_version: "5.5.5"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.53.0

## Docker configuration.
#docker_container_name: drupal-vm
#docker_image_name: drupal-vm
#docker_image_path: ~/Downloads

## Other configuration.
#dashboard_install_dir: /var/www/dashboard
#known_hosts_path: ~/.ssh/known_hosts
#hostname_configure: true
#hostname_fqdn: "{{ vagrant_hostname }}"
#ssh_home: "{{ drupal_core_path }}"

#nginx
nginx_remove_default_vhost: true
nginx_ppa_use: true

nginx_root_base_path: "/var/www"
nginx_package_name: "openresty"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

