---
hostname: origami2.local

# database
db_backend: mysql
db_name: origami
db_user: origami
db_password: origami

app_admin_user: admin
app_admin_password: admin

firewall_allowed_tcp_ports:
  - "22"    # ssh
  - "25"    # smtp
  - "2200"  # ansible
  - "80"    # varnish
  - "443"   # https
  - "3306"  # mysql
  - "8080"  # nginx

machines:
  dev01:
    frontend: true
    provider: "{{ vagrant_provider }}"
    box: "{{ vagrant_box }}"
    ip: "192.168.10.10"

    memory: "{{ vagrant_memory }}"
    cpus: "{{ vagrant_cpus }}"

    folders:
      -
        map: ./backend
        to: "{{ deploy_current_path }}/backend"
      -
        map: ./frontend
        to: "{{ deploy_current_path }}/frontend"

nginx_vhosts:
  - server_name: "www.{{ hostname }}"
    server_name_redirect: "{{ hostname }}"
    root: "{{ deploy_current_path }}/frontend/public"
    template: "symfony4.j2"

  - server_name: "api.{{ hostname }}"
    root: "{{ deploy_current_path }}/backend/public"
    template: "symfony4.j2"

  - server_name: "admin.{{ hostname }}"
    root: "{{ deploy_current_path }}/backend/public"
    template: "symfony4.j2"

  - server_name: "logs.{{ hostname }}"
    root: "{{ deploy_base_path }}/pimpmylog"
    template: "php-tool.j2"

  - server_name: "mail.{{ hostname }}"
    template: "proxy.j2"
    root: "/opt/mailhog"
    backend_port: 8025

  - server_name: "redis.{{ hostname }}"
    root: "{{ deploy_base_path }}/phpredmin/public"
    template: "php-tool.j2"


installed_extras:
  - mailhog
  - phpredmin
  - pimpmylog
  - xdebug
# - elasticsearch
# - java
# - memcached
# - ruby
# - selenium
# - solr