---
- name: restart nginx
  service: name=openresty state=restarted

- name: validate nginx configuration
  command: openresty -t -c /etc/openresty/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=openresty state=reloaded
